Feature/get customer by cpf
marcoselli/uaifood pull request #8
Opened 2024-10-31 16:05 UTC by Giulianna-Tonin

Buscar Customer pro CPF
Testes unitários
Testes de integracao 
swagger

2024-11-01 00:22 UTC, marcoselli requested changes

2024-11-01 00:22 UTC, marcoselli commented on src/main/kotlin/br/edu/uaifood/adapters/CustomerRepository.kt
> +    fun findByCpf(cpf: String): Optional<CustomerPersisted>
Nesse caso ao invés do Optional não seria mais interessante retornar "CustomerPersisted?", seguimos o padrão para utilizar as features do própio Kotlin

2024-11-01 00:22 UTC, marcoselli commented on src/main/kotlin/br/edu/uaifood/exception/CustomerValidationException.kt
Faltou mapear a expcetion em br.edu.uaifood.exception.ExceptionControllerAdvice.kt

2024-11-01 00:22 UTC, marcoselli commented on src/main/kotlin/br/edu/uaifood/ports/inbound/api/customer/CustomerController.kt
> +            val customer = service.findCustomerByCpf(Customer.validateCpf(cpf))
Não é necessário esse try-catch ao mapear a exception no ControllerAdvice

2024-11-02 03:34 UTC, Giulianna-Tonin commented on src/main/kotlin/br/edu/uaifood/adapters/CustomerRepository.kt
> +    fun findByCpf(cpf: String): Optional<CustomerPersisted>
done

2024-11-02 03:34 UTC, Giulianna-Tonin commented on src/main/kotlin/br/edu/uaifood/exception/CustomerValidationException.kt
done

2024-11-02 03:34 UTC, Giulianna-Tonin commented on src/main/kotlin/br/edu/uaifood/ports/inbound/api/customer/CustomerController.kt
> +            val customer = service.findCustomerByCpf(Customer.validateCpf(cpf))
done

2024-11-04 21:53 UTC, marcoselli approved these changes

2024-11-04 21:54 UTC, marcoselli approved these changes

2024-11-04 22:07 UTC, merged